export const SHOPS = {
  milksha: {
    name: "迷客夏",
    sub: "Milksha",
    category: "drink",
    logo: "milksha_logo.png",
    imgs: ["milksha_menu.jpg"],
    url: "https://www.milksha.com/",
  },
  damingtea: {
    name: "大茗本味製茶堂",
    sub: "DAMING",
    category: "drink",
    logo: "damingtea_logo.png",
    imgs: ["damingtea_menu.png"],
    url: "https://www.damingtea.com.tw/",
  },
  truedan: {
    name: "珍煮丹",
    sub: "TRUEDAN",
    category: "drink",
    logo: "truedan_logo.png",
    imgs: ["truedan_menu.jpg"],
    url: "https://www.truedan.com.tw/",
  },
  dejeng: {
    name: "得正",
    sub: "Dejeng",
    category: "drink",
    logo: "dejeng_logo.png",
    imgs: ["dejeng_menu.jpg"],
    url: "https://dejeng.com/",
  },
  "50lan": {
    name: "50嵐",
    sub: "",
    category: "drink",
    logo: "50lan_logo.png",
    imgs: ["50lan_menu.jpg"],
    url: "https://www.xn--50-wg2du59ik3f.tw/",
  },
  minimini: {
    name: "米里米里",
    sub: "MINI-MINI",
    category: "drink",
    logo: "minimini_logo.png",
    imgs: ["minimini_menu.jpg"],
    url: "https://minimini-tw.com/",
  },
  macutea: {
    name: "麻古茶坊",
    sub: "MACU",
    category: "drink",
    logo: "macutea_logo.png",
    imgs: ["macutea_menu.jpg"],
    url: "https://www.macutea.com.tw/",
  },
  "8yotea": {
    name: "八曜和茶",
    sub: "ハチヨウワチヤ",
    category: "drink",
    logo: "8yotea_logo.png",
    imgs: ["8yotea_menu.jpg"],
    url: "https://8yotea.com/",
  },
  youindrink: {
    name: "有飲",
    sub: "",
    category: "drink",
    logo: "youindrink_logo.png",
    imgs: ["youindrink_menu.webp"],
    url: "https://www.youindrink.com/",
  },
  chingshanteashop: {
    name: "青山茶行",
    sub: "",
    category: "drink",
    logo: "chingshanteashop_logo.jpg",
    imgs: ["chingshanteashop_menu.jpg"],
    url: "https://www.facebook.com/1982teashop",
    linkLabel: "官方 Facebook",
  },
  peaktea: {
    name: "青山",
    sub: "Peak Tea",
    category: "drink",
    logo: "peaktea_logo.png",
    imgs: ["peaktea_menu.webp"],
    url: "https://peak-tea.com/",
  },
  chingshin: {
    name: "清心福全",
    sub: "",
    category: "drink",
    logo: "chingshin_logo.png",
    imgs: ["chingshin_menu.jpg"],
    url: "https://www.chingshin.tw/?lang=cht",
  },
  aniceholiday: {
    name: "一沐日",
    sub: "A NICE HOLIDAY",
    category: "drink",
    logo: "aniceholiday_logo.jpg",
    imgs: ["aniceholiday_menu.jpg"],
    url: "https://www.imuz.com.tw/",
  },
  bogteashop: {
    name: "波哥茶飲",
    sub: "",
    category: "drink",
    logo: "bogteashop_logo.png",
    imgs: ["bogteashop_menu.jpg"],
  },
  shuansenbeverages: {
    name: "双生綠豆沙牛奶",
    sub: "",
    category: "drink",
    logo: "shuansenbeverages_logo.png",
    imgs: ["shuansenbeverages_menu.jpg"],
    url: "https://www.facebook.com/ShuansenBeverages",
    linkLabel: "官方 Facebook",
  },
  lairitea: {
    name: "來日方茶",
    sub: "",
    category: "drink",
    logo: "lairitea_logo.jpg",
    imgs: ["lairitea_menu.jpg"],
    url: "https://www.instagram.com/lairi_tea_2023/",
    linkLabel: "官方 Instagram",
  },
  tptea: {
    name: "茶湯會",
    sub: "TP-TEA",
    category: "drink",
    logo: "tptea_logo.png",
    imgs: ["tptea_menu.jpg"],
    url: "https://tw.tp-tea.com/",
  },
  liketeashop: {
    name: "老賴茶棧",
    sub: "",
    category: "drink",
    logo: "liketeashop_logo.jpg",
    imgs: ["liketeashop_menu.jpg"],
    url: "https://www.liketeashop.com/",
  },
  kebuke: {
    name: "可不可熟成紅茶",
    sub: "KEBUKE",
    category: "drink",
    logo: "kebuke_logo.png",
    imgs: ["kebuke_menu.jpg"],
    url: "https://kebuke.com/",
  },
  xuanfuresidence: {
    name: "宣福居",
    sub: "",
    category: "drink",
    logo: "xuanfuresidence_logo.jpg",
    imgs: ["xuanfuresidence_menu.png"],
  },
  hechaloutea: {
    name: "鶴茶樓",
    sub: "hechaloutea",
    category: "drink",
    logo: "hechaloutea_logo.jpeg",
    imgs: ["hechaloutea_menu.webp"],
    url: "https://hechaloutea.com.tw/",
  },
  guiji: {
    name: "龜記",
    sub: "guiji",
    category: "drink",
    logo: "guiji_logo.jpg",
    imgs: ["guiji_menu.jpg"],
    url: "https://www.guiji-group.com/",
  },
  napteazzz: {
    name: "再睡5分鐘",
    sub: "NAP TEA",
    category: "drink",
    logo: "npatea_logo.png",
    imgs: ["naptea_menu.avif"],
    url: "https://www.napteazzz.com/",
  },
  coco: {
    name: "CoCo都可",
    sub: "CoCo",
    category: "drink",
    logo: "coco_logo.jpg",
    imgs: ["coco_menu.jpg"],
    url: "https://www.coco-tea.com/",
  },
  teatop: {
    name: "TEA TOP第一味",
    sub: "TEA TOP",
    category: "drink",
    logo: "teatop_logo.png",
    imgs: ["teatop_menu.jpg"],
    url: "https://www.teatop.com.tw/",
  },
  toptiertea: {
    name: "特好喝",
    sub: "TOP TIER TEA",
    category: "drink",
    logo: "toptiertea_logo.webp",
    imgs: ["toptiertea_menu.webp"],
    url: "https://toptiertea.com.tw/",
  },
  "19teahouse": {
    name: "拾汣茶屋",
    sub: "",
    category: "drink",
    logo: "19teahouse_logo.png",
    imgs: ["19teahouse_menu.png"],
    url: "https://www.19teahouse.com/",
  },
  wootea: {
    name: "五桐號",
    sub: "WOOTEA",
    category: "drink",
    logo: "wootea_logo.png",
    imgs: ["wootea_menu.jpg"],
    url: "https://www.wootea.com/",
  },
  lucymama: {
    name: "露西媽媽",
    sub: "LUCY MAMA PASTA",
    category: "food",
    logo: "lucymama_logo.jpg",
    imgs: ["lucymama_menu1.jpg", "lucymama_menu2.jpg"],
  },
  guijihandmadedumplingrestaurant: {
    name: "桂記手工水餃",
    sub: "",
    category: "food",
    logo: "guijihandmadedumplingrestaurant_logo.jpg",
    imgs: ["guijihandmadedumplingrestaurant_menu.jpg"],
  },
  laotsengbeefnoodles: {
    name: "老曾牛肉麵",
    sub: "",
    category: "food",
    logo: "laotsengbeefnoodles_logo.jpg",
    imgs: ["laotsengbeefnoodles_menu.jpg"],
  },
  liufamilyduckmeat: {
    name: "劉家鴨肉",
    sub: "",
    category: "food",
    logo: "liufamilyduckmeat_logo.jpg",
    imgs: ["liufamilyduckmeat_menu.jpg"],
  },
  cometogether: {
    name: "作伙來",
    sub: "",
    category: "food",
    logo: "cometogether_logo.jpg",
    imgs: ["cometogether_menu.jpg"],
  },
  fengangelicaduck: {
    name: "豐當歸鴨",
    sub: "",
    category: "food",
    logo: "fengangelicaduck_logo.jpg",
    imgs: ["fengangelicaduck_menu.jpg"],
  },
  niuzu: {
    name: "牛族",
    sub: "",
    category: "food",
    logo: "niuzu_logo.jpg",
    imgs: [
      "niuzu_menu1.jpg",
      "niuzu_menu2.jpg",
      "niuzu_menu3.jpg",
      "niuzu_menu4.jpg",
    ],
  },
  dandanburger: {
    name: "丹丹漢堡",
    sub: "",
    category: "food",
    logo: "dandanburger_logo.jpg",
    imgs: ["dandanburger_menu.jpeg"],
  },
  burgerking: {
    name: "漢堡王",
    sub: "",
    category: "food",
    logo: "burgerking_logo.png",
    imgs: [],
    url: "https://www.burgerking.com.tw/",
  },
  mcdonalds: {
    name: "麥當勞",
    sub: "",
    category: "food",
    logo: "mcdonalds_logo.png",
    imgs: [],
    url: "https://www.mcdonalds.com/tw/zh-tw.html",
  },
  kfc: {
    name: "肯德基",
    sub: "",
    category: "food",
    logo: "kfc_logo.png",
    imgs: [],
    url: "https://www.kfcclub.com.tw/",
  },
  ahzhenfriedchicken: {
    name: "阿珍炸雞",
    sub: "",
    category: "food",
    logo: "ahzhenfriedchicken_logo.jpg",
    imgs: ["ahzhenfriedchicken_menu.jpg"],
  },
};

export function findShopByName(name, category) {
  return Object.entries(SHOPS).find(([, shop]) => {
    const sameCategory = category ? shop.category === category : true;
    return sameCategory && shop.name === name;
  });
}
